parameters:

services:
    App\Doctrine\PrefixedNamingStrategy:
        arguments:
            $prefix: 'appy_'
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Doctrine/'
